version: '3.8'  # Removed the #

services:
  postgres:
    image: postgres:latest
    container_name: school-postgres
    environment:
      POSTGRES_DB: schooldb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: bencoderr
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d schooldb"]
      interval: 2s
      timeout: 3s
      retries: 15
      start_period: 5s
    networks:
      - school-network

  school-app:
    build: .
    container_name: school-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/schooldb
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: bencoderr
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - school-network

volumes:
  postgres-data:

networks:
  school-network:
    driver: bridge