CREATE TABLE student (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    full_name VARCHAR(120) NOT NULL,
    email VARCHAR(120) NOT NULL UNIQUE
);
ALTER TABLE student ADD COLUMN surname VARCHAR(255) NOT NULL AFTER full_name;

