package com.school.config;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Info;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

//Api documentatino of swagger will be to help linking front end with backend 
@Configuration
public class OpenApiConfig {

    @Bean
    public OpenAPI schoolApi() {
        return new OpenAPI().info(
                new Info().title("Edusphere API")
                          .version("v1")
                          .description(" docs auto-generated by springdoc"));
    }
}
